.TH utfstringinfo 1 "05 Jul 2022"
.SH NAME
utfstringinfo \- Analyze a UTF-8 encoded string
.SH SYNOPSIS
.B utfstring [string]
.I 
.SH DESCRIPTION
.B utfstringinfo
reads arguments or, if no arguments are provided, stdin and for every single character it finds it shows the UTF-8 character sequence, the unicode code-point 
and, if applicable, the utftex command that can be used to generate the symbol.

.SH AUTHOR
Bart Pieters
.SH LICENSE
GNU GENERAL PUBLIC LICENSE Version 3
.SH VERSION
1.0
.SH SEE ALSO
.B 
